name = "mesdeparts-ch"
main = "cloudflare-worker/worker.js"
compatibility_date = "2025-12-17"

routes = [
  { pattern = "api.mesdeparts.ch/api/*" }
]

[vars]
RT_BACKEND_ORIGIN = "https://api-origin.mesdeparts.ch"
